server:
  port: 7001
eureka:
  server:
    enable-self-preservation: false     # 设置为false表示关闭保护模式
    eviction-interval-timer-in-ms: 1000 # 设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
  client:
    # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka
    # 不把自己注册到eureka服务列表
    register-with-eureka: false
    # 拉取eureka服务信息
    fetch-registry: false #false表示自己就是注册中心，不需要从注册中心获取注册列表信息
  instance: # eureak实例定义
    #    hostname: eureka-7001.com # 定义Eureka实例所在的主机名称
    hostname: eureka-7001.com # 定义Eureka实例所在的主机名称