server:
  port: 80          # 服务端口
spring:
  application:
    name: springcloud-ribbon-server
eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
    register-with-eureka: false    # 当前的微服务不注册到eureka之中
